routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/.well-known/pki-validation/F34F3664E3D4504ED609FF340B723EBD.txt', function() {
    $path = base_path() . '/.well-known/pki-validation/F34F3664E3D4504ED609FF340B723EBD.txt';
    header('Content-Type: text/plain');
    header('Content-Disposition: inline; filename="F34F3664E3D4504ED609FF340B723EBD.txt"');
    readfile($path);
});

Route::get('/', 'FrontendController@index');

Route::get('/faq',  'FrontendController@faq');

Route::get('/account-settings',  'FrontendController@accountSettings');

Route::get('/cart',  'FrontendController@cart');

Route::get('/my-order',  'FrontendController@myOrder');

Route::get('/order-history',  'FrontendController@orderHistory');

Route::get('/order-tracking',  'FrontendController@orderTracking');

Route::get('/payment-methods',  'FrontendController@paymentMethods');

Route::get('/wallet',  'FrontendController@wallet');

Route::get('/wishlist',  'FrontendController@wishlist');

Route::get('/product/{product}',  'FrontendController@getProduct')->name('get-product');

/*Route::get('/', function () {
    return view('greenergy.greenergy');
});*/

Route::namespace('Greenergy')->prefix('admin')->group(function (){
    Route::get('call_requests', 'CallRequestsController@index')->name('call-requests.index')->middleware('auth');
    Route::post('call-requests', 'CallRequestsController@store')->name('call-requests.store');
});

Route::namespace('Admin')->prefix('admin')->middleware('auth')->group(function () {
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/get-category-by-main-category', 'CategoriesController@getCategoryByMainCategory')
        ->name('get-categories-by-main-category-id');
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::post('assign-to-roles/{role_id}', 'PermissionsController@assignToRoles')->name('assign-to-roles');
    Route::delete('remove-role/{id}', 'PermissionsController@removeRole')->name('remove-from-role');
    Route::post('assign-permissions/{permission_id}', 'RolesController@assignPermissions')->name('assign-permissions');
    Route::delete('remove-permission/{id}', 'RolesController@removePermission')->name('remove-permission');
    Route::resource('products', 'ProductsController');
    Route::post('products/add-packages/{product}', 'ProductsController@addPackages')->name('add-packages');
    Route::delete('products/remove-package/{product}', 'ProductsController@removePackage')->name('remove-package');
    Route::get('download-excel-template', 'ProductsController@downloadExcelTemplate')->name('download-excel-template');
    Route::get('products/upload/bulk-products', 'ProductsController@bulkUpload')->name('products.bulk-upload');
    Route::post('products/store/bulk-products', 'ProductsController@storeBulkUpload')->name('products.store-bulk-upload');
    Route::post('products/publish/{id}', 'ProductsController@publish')->name('products.publish');
    Route::post('products/unpublish/{id}', 'ProductsController@unPublish')->name('products.unpublish');

    //Referrals routes
    Route::resource('referrals', 'ReferralsController');

    //Users routes
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::patch('users/{id}/enable', 'UsersController@enable')->name('users.enable');
    Route::patch('users/{id}/disable', 'UsersController@disable')->name('users.disable');
    Route::get('users/{user}', 'UsersController@details')->name('users.details');


    // Gold Price route
    Route::get('gold-prices', 'GoldPriceController@index')->name('gold-price-list');
    Route::get('gold-prices/create', 'GoldPriceController@create')->name('gold-price.create');
    Route::post('gold-prices', 'GoldPriceController@store')->name('gold-price.store');

    //Banner Routes
    Route::resource('banners', 'BannersController');
    Route::put('banners/status-change/{banner}','BannersController@changeStatus')->name('banner-status-change');

    //Product Call Request
    Route::get('product-call-request-list', 'ProductCallRequestsController@callRequestList')->name('product-call-request-list');


});


//Auth::routes();
Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Admin/Referral.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class Referral extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/ReferralsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Repositories\Referral\ReferralRepositoryContract;
use Illuminate\Http\Request;

class ReferralsController extends Controller
{
    /**
     * @var ReferralRepositoryContract
     */
    protected $referrals;

    public function __construct(ReferralRepositoryContract $referrals)
    {
        $this->referrals = $referrals;
    }

    /*
     * show all referrals
     * */
    public function index()
    {
        $referrals = $this->referrals->paginate(10);
        return view('admin.referrals.index', compact('referrals'));
    }

    /*
     * create referral
     * */
    public function create()
    {
        return view('admin.referrals.create');
    }

    /*
     * send referral
     * */
    public function store(Request $request)
    {
        $data = $request->validate([
           'phone' => 'required|digits:10',
           'message' => 'required'
        ]);
        $this->referrals->create($data);
        return redirect(route('referrals.index'));
    }
}

resources/views/admin/referrals/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('referrals.index')}}">Referrals</a></li>
                <li class="breadcrumb-item active" aria-current="page">Send Referral</li>
            </ol>
        </nav>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Send Referral') }}</div>

                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data" action="{{ route('referrals.store') }}">
                            @csrf

                            @include('admin.referrals.form')

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/referrals/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Roles</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit Role</li>
            </ol>
        </nav>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Edit Role') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('roles.update', $role->id) }}">
                            @csrf
                            @method('PUT')

                            @include('admin.roles.form')

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/referrals/form.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>
    <div class="col-md-6">
        <input id="phone" maxlength="10" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone"
               value="{{ isset($referral->phone) ? $referral->phone : old('phone') }}" required autocomplete="phone">

        @error('phone')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Message') }}</label>

    <div class="col-md-6">
        <textarea id="message" type="text" class="form-control @error('message') is-invalid @enderror" name="message"
                  required autocomplete="message">{{ isset($referral->message) ? $referral->message : old('message') }}</textarea>
        @error('message')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

resources/views/admin/referrals/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Referrals</li>
            </ol>
        </nav>

        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-primary" href="{{ route('referrals.create') }}">
                            {{ __('Send Referral') }}
                        </a>
                    </div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>Phone</th>
                                <th>Message</th>
                                <th>Send At</th>
                            </tr>

                            </thead>
                            <tbody>
                            @foreach ($referrals as $key => $referral)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $referral->phone }}</a></td>
                                    <td>{{ $referral->message }}</td>
                                    <td>{{ date('d-M-Y H:i:s') }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        {{$referrals->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            $('.pagination').addClass('justify-content-end')
        });
    </script>
@endpush

resources/views/admin/referrals/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Roles</a></li>
                <li class="breadcrumb-item active" aria-current="page">Role Details</li>
            </ol>
        </nav>

        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{ __('Role Details') }}
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row">
                                    <label class="control-label col-sm-2" for="email">Role:</label>
                                    <div class="col-sm-10">
                                        <strong>{{ $role->role }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <label class="control-label col-sm-2" for="email">Slug:</label>
                                    <div class="col-sm-10">
                                        <strong>{{ $role->slug }}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <label class="control-label" for="email">Description:</label>
                                <p>
                                    <strong>@if(is_null($role->description)) Not Provided @else {{$role->description}} @endif</strong>
                                </p>
                            </div>
                        </div>
                        @if(count($assigned_permissions))
                            <hr>
                            <h4>Assigned Permissions</h4>
                            <div id="permissions" style="margin: 15px 3px 15px 0;">
                                @foreach($assigned_permissions as $permission)
                                    <div style="background-color: pink;padding: 3px 8px;font-weight: bold; display: inline-block">
                                        <form action="{{route('remove-permission', $permission->pivot->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <span>{{$permission->permission}}</span>
                                            <input type="hidden" value="{{$permission->id}}">
                                            <input type="submit" value="X" name="delete" class="btn btn-sm btn-danger" style="padding: 0 4px">
                                        </form>
                                    </div>
                                @endforeach
                            </div>
                        @endif
                        <h4>Assign Permissions</h4>
                        <form action="{{route('assign-permissions', $role->id)}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <select class="form-control" id="sel1" name="permissions[]" multiple>
                                    <option>Select Permissions</option>
                                    @foreach($permissions as $permission)
                                        <option value="{{$permission->id}}">{{$permission->permission}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <input type="submit" name="submit" class="btn btn-info btn-sm" value="Assign">
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection