routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/.well-known/pki-validation/F34F3664E3D4504ED609FF340B723EBD.txt', function() {
    $path = base_path() . '/.well-known/pki-validation/F34F3664E3D4504ED609FF340B723EBD.txt';
    header('Content-Type: text/plain');
    header('Content-Disposition: inline; filename="F34F3664E3D4504ED609FF340B723EBD.txt"');
    readfile($path);
});

Route::get('/', 'FrontendController@index');

Route::get('/faq',  'FrontendController@faq');

Route::get('/account-settings',  'FrontendController@accountSettings');

Route::get('/cart',  'FrontendController@cart');

Route::get('/my-order',  'FrontendController@myOrder');

Route::get('/order-history',  'FrontendController@orderHistory');

Route::get('/order-tracking',  'FrontendController@orderTracking');

Route::get('/payment-methods',  'FrontendController@paymentMethods');

Route::get('/wallet',  'FrontendController@wallet');

Route::get('/wishlist',  'FrontendController@wishlist');

Route::get('/product/{product}',  'FrontendController@getProduct')->name('get-product');

/*Route::get('/', function () {
    return view('greenergy.greenergy');
});*/

Route::namespace('Greenergy')->prefix('admin')->group(function (){
    Route::get('call_requests', 'CallRequestsController@index')->name('call-requests.index')->middleware('auth');
    Route::post('call-requests', 'CallRequestsController@store')->name('call-requests.store');
});

Route::namespace('Admin')->prefix('admin')->middleware('auth')->group(function () {
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/get-category-by-main-category', 'CategoriesController@getCategoryByMainCategory')
        ->name('get-categories-by-main-category-id');
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::post('assign-to-roles/{role_id}', 'PermissionsController@assignToRoles')->name('assign-to-roles');
    Route::delete('remove-role/{id}', 'PermissionsController@removeRole')->name('remove-from-role');
    Route::post('assign-permissions/{permission_id}', 'RolesController@assignPermissions')->name('assign-permissions');
    Route::delete('remove-permission/{id}', 'RolesController@removePermission')->name('remove-permission');
    Route::resource('products', 'ProductsController');
    Route::post('products/add-packages/{product}', 'ProductsController@addPackages')->name('add-packages');
    Route::delete('products/remove-package/{product}', 'ProductsController@removePackage')->name('remove-package');
    Route::get('download-excel-template', 'ProductsController@downloadExcelTemplate')->name('download-excel-template');
    Route::get('products/upload/bulk-products', 'ProductsController@bulkUpload')->name('products.bulk-upload');
    Route::post('products/store/bulk-products', 'ProductsController@storeBulkUpload')->name('products.store-bulk-upload');
    Route::post('products/publish/{id}', 'ProductsController@publish')->name('products.publish');
    Route::post('products/unpublish/{id}', 'ProductsController@unPublish')->name('products.unpublish');

    //Referrals routes
    Route::resource('referrals', 'ReferralsController');

    //Users routes
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::patch('users/{id}/enable', 'UsersController@enable')->name('users.enable');
    Route::patch('users/{id}/disable', 'UsersController@disable')->name('users.disable');
    Route::get('users/{user}', 'UsersController@details')->name('users.details');


    // Gold Price route
    Route::get('gold-prices', 'GoldPriceController@index')->name('gold-price-list');
    Route::get('gold-prices/create', 'GoldPriceController@create')->name('gold-price.create');
    Route::post('gold-prices', 'GoldPriceController@store')->name('gold-price.store');

    //Banner Routes
    Route::resource('banners', 'BannersController');
    Route::put('banners/status-change/{banner}','BannersController@changeStatus')->name('banner-status-change');

    //Product Call Request
    Route::get('product-call-request-list', 'ProductCallRequestsController@callRequestList')->name('product-call-request-list');


});


//Auth::routes();
Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Admin/Permission.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    protected $fillable = [ 'permission', 'slug', 'description' ];

    public function roles() {
        return $this->belongsToMany( '\App\Models\Admin\Role',
            'permission_role', 'permission_id', 'role_id'
        )->withPivot('id');
    }
}

app/Http/Controllers/Admin/PermissionsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Admin\Role;
use Illuminate\Http\Request;
use App\Models\Admin\Permission;
use App\Repositories\Permission\PermissionRepositoryContract;
use Illuminate\Support\Str;

class PermissionsController extends Controller
{
    protected $permission;

    public function __construct(PermissionRepositoryContract $permission)
    {
        $this->permission = $permission;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = $this->permission->paginate(10);

        return view('admin.permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->merge(['slug'=>Str::slug($request->permission)]);
        $input = $request->validate([
            'permission' => 'required',
            'slug' => 'required|unique:permissions,slug'
        ]);

        $this->permission->create($input);

        return redirect(route('permissions.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $permission = $this->permission->getById($id);
        $assigned_roles = $permission->roles()->select('roles.id','role')->get();
        $roles = Role::select('id', 'role')->get();
        return view('admin.permissions.show', compact('permission', 'roles', 'assigned_roles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = $this->permission->getById($id);
        return view('admin.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->merge(['slug'=>Str::slug($request->permission)]);
        $input = $request->validate([
            'permission' => 'required',
            'slug' => 'required|unique:permissions,slug,'.$id
        ]);

        $this->permission->update($request->all()+['slug'=>Str::slug($request->permission)], $id);

        return redirect(route('permissions.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->permission->delete($id);

        return redirect(route('permissions.index'));
    }

    public function assignToRoles(Request $request, $permission_id)
    {
        $permission = Permission::find($permission_id);
        $permission->roles()->sync($request->roles);
        return back();
    }

    public function removeRole($id)
    {
        \DB::table('permission_role')->where('id', $id)->delete();

        return back();
    }
}

resources/views/admin/permissions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('permissions.index')}}">Permissions</a></li>
                <li class="breadcrumb-item active" aria-current="page">Create Permission</li>
            </ol>
        </nav>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Create Permission') }}</div>

                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data" action="{{ route('permissions.store') }}">
                            @csrf

                            @include('admin.permissions.form')

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/permissions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('permissions.index')}}">Permissions</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit Permission</li>
            </ol>
        </nav>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Edit Permission') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('permissions.update', $permission->id) }}">
                            @csrf
                            @method('PUT')

                            @include('admin.permissions.form')

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/permissions/form.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Permission') }}</label>
    <div class="col-md-6">
        <input id="permission" type="text" class="form-control @error('permission') is-invalid @enderror" name="permission"
               value="{{ isset($permission->permission) ? $permission->permission : old('permission') }}" required autocomplete="permission">

        @error('permission')
        <span class="invalid-feedback" permission="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

    <div class="col-md-6">
        <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description"
                  autocomplete="description">{{ isset($permission->description) ? $permission->description : old('description') }}</textarea>
        @error('description')
        <span class="invalid-feedback" permission="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

resources/views/admin/permissions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Permissions</li>
            </ol>
        </nav>

        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-primary" href="{{ route('permissions.create') }}">
                            {{ __('Create New Permission') }}
                        </a>
                    </div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>Permission</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>

                            </thead>
                            <tbody>
                            @foreach($permissions as $key => $permission)
                                <tr>
                                    <td>{{$key+1}}</td>
                                    <td><a href="{{route('permissions.show', $permission->id)}}">{{$permission->permission}}</a></td>
                                    <td>
                                        <a href="{{route('permissions.edit', $permission->id)}}" class="btn btn-success">
                                            Edit
                                        </a>
                                    </td>
                                    <td>
                                        <form method="POST" action="{{route('permissions.destroy', $permission->id)}}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger">
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        {{$permissions->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            $('.pagination').addClass('justify-content-end')
        });
    </script>
@endpush

resources/views/admin/permissions/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('permissions.index')}}">Permissions</a></li>
                <li class="breadcrumb-item active" aria-current="page">Permission Details</li>
            </ol>
        </nav>

        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{ __('Permission Details') }}
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row">
                                    <label class="control-label col-sm-3" for="email">Permission:</label>
                                    <div class="col-sm-9">
                                        <strong>{{ $permission->permission }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <label class="control-label col-sm-3" for="email">Slug:</label>
                                    <div class="col-sm-9">
                                        <strong>{{ $permission->slug }}</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <label class="control-label" for="email">Description:</label>
                                <p>
                                    <strong>@if(is_null($permission->description)) Not Provided @else {{$permission->description}} @endif</strong>
                                </p>
                            </div>
                        </div>
                        @if(count($assigned_roles))
                            <hr>
                            <h4>Assigned Permissions</h4>
                            <div id="roles" style="margin: 15px 3px 15px 0;">
                                @foreach($assigned_roles as $role)
                                    <div style="background-color: pink;padding: 3px 8px;font-weight: bold; display: inline-block">
                                        <form action="{{route('remove-from-role', $role->pivot->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <span>{{$role->role}}</span>
                                            <input type="hidden" value="{{$role->id}}">
                                            <input type="submit" value="X" name="delete" class="btn btn-sm btn-danger" style="padding: 0 4px">
                                        </form>
                                    </div>
                                @endforeach
                            </div>
                        @endif
                        <h4>Assign this permission to roles</h4>
                        <form action="{{route('assign-to-roles', $permission->id)}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <select class="form-control" id="sel1" name="roles[]" multiple>
                                    <option>Select Roles</option>
                                    @foreach($roles as $role)
                                        <option value="{{$role->id}}">{{$role->role}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <input type="submit" name="submit" class="btn btn-info btn-sm" value="Assign">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection